### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattfarina** [go-openapi/swaggersocket#8]
If no license is provided it's proprietary. What license is this under?

**Comment by GlenDC** [comment]
@casualjim can probably give a definitive answer to this question.

But I would guess it's under Apache 2, the same as all other go-openapi repositories. swaggerrocket has only recently be gifted to go-openapi, and it's a fairly new project. So I think the license has just been forgotten.

**Comment by casualjim** [comment]
I'll add the Apache 2 license, so it's inline with everything else in this series of repos.
We also need a readme.

**Comment by casualjim** [comment]
license and readme have been added
